Ualch9/asyncify/region picker
OneBusAway/onebusaway-ios pull request #630
Opened 2023-01-17 10:21 UTC by ualch9

https://user-images.githubusercontent.com/22162410/212872734-5c3fcfbd-ac81-4da4-98eb-e4e78670d1bf.mov

2023-01-27 23:01 UTC, ualch9 commented
Hm, want to try one more thing with one-time location authorization...

2023-01-28 12:39 UTC, ualch9 commented
> Hm, want to try one more thing with one-time location authorization...

Never mind, ready for review.

2023-01-28 17:07 UTC, aaronbrethorst commented
@ualch9 can you take a quick pass through the commits here and squash where appropriate?

2023-01-29 14:02 UTC, ualch9 commented
Rebased, added some comments, and fixed some localization. I hope this helps with your review.

2023-01-29 17:43 UTC, aaronbrethorst commented
@ualch9 awesome, I'll review today.

2023-01-30 04:02 UTC, aaronbrethorst requested changes
Looks great! I noticed a couple small UI changes and had a couple pieces of feedback/questions for you. Looking forward to getting this shipped. it's super cool.

2023-01-30 04:02 UTC, aaronbrethorst commented on OBAKitCore/Network/APIService.swift
> +    var logger: os.Logger { get }
👍

2023-01-30 04:02 UTC, aaronbrethorst commented on OBAKitTests/Modeling/Regions Model Service Tests/RegionsModelOperationTests.swift
> +        let response = try await regionsAPIService.getRegions(apiPath: regionsAPIPath)
🎉

2023-01-30 14:35 UTC, ualch9 commented on OBAKit/Onboarding/RegionPicker/RegionCustomForm.swift
> +struct RegionCustomForm: View {
#635

2023-01-30 14:35 UTC, ualch9 commented on OBAKitCore/Location/Regions/RegionsService.swift
> +        // FIXME: Audit which delegates are doing stuff on background thread, when they should be on Main.
#635

2023-01-30 15:18 UTC, ualch9 commented on OBAKit/Onboarding/RegionPicker/RegionCustomForm.swift
> +                TextField("https://api.tampa.onebusaway.org/api/", text: $baseURLString)
agh!

2023-01-30 16:52 UTC, aaronbrethorst commented
Awesome thanks @ualch9!

2023-01-30 16:52 UTC, merged