Fix: issue 629
OneBusAway/onebusaway-ios pull request #714
Opened 2024-02-23 04:37 UTC by aaryankotharii

##### This PR migrates regions storage from UserDefaults to FileManager. Same file structure followed as mentioned in issue description. 

<hr>
fixes issue: #629 
<hr>

### Code Changes

- Created `FileManagerProtocol` to abstract FileManager operations for testability.
- Updated RegionService to store and fetch defaultRegion and custom Regions in File system. 
- Created `FileManagerMock` and updated `RegionsServiceTests`.

2024-02-23 04:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-ios?pullRequest=714) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-ios?pullRequest=714) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-ios?pullRequest=714) it.</sub>

2024-02-24 00:48 UTC, aaronbrethorst commented
Thank you @aaryankotharii! I'll review and get back to you soon!

2024-03-13 07:03 UTC, ualch9 requested changes
Thanks for this PR, @aaryankotharii, we really appreciate it! Great job with updating the tests to ensure quality! I have a few concerns with the layering and the addition of more state.

Also, please test that users who update are able to continue using the app with no interruptions. For example, regions are currently stored in UserDefaults and this PR changes it to storing on disk. Please run the app in a current App Store version, then run a version of the app with this PR and validate that the user can continuing the app without it being confused on the currently selected region. 

Please ask questions if you have any, or are unclear about my comments!

2024-03-17 00:19 UTC, aaryankotharii commented
Hello @ualch9, I have made the following changes as requested above.
1. replaced `PropertyListEncoder / Decoder` with `JSONEncoder / Decoder`.
2. replaced enum `FileDestination` logic with simple static constants in `RegionsService`.
3. renamed `FileManagerProtocol` to `RegionsServiceFileManagerProtocol`.

2024-03-17 17:48 UTC, ualch9 commented
Thank you @aaryankotharii! Apologies for the delayed turnaround in reviewing, I'll get to this ASAP.

2024-03-17 17:59 UTC, aaryankotharii commented
no worries @ualch9, but there are a few migration issues I'm not sure how to address. for example, how to approach fetching custom regions, of existing users, which are stored in userdefaults ?

2024-03-17 18:03 UTC, ualch9 commented
> no worries @ualch9, but there are a few migration issues I'm not sure how to address. for example, how to approach fetching custom regions, of existing users, which are stored in userdefaults ?

Excellent question... @aaronbrethorst, do you have any insight on if custom regions are used enough for us to support a migration path?

2024-03-17 18:15 UTC, aaronbrethorst commented
I would not worry about custom regions at this time. Thanks for checking!

2024-03-23 16:15 UTC, ualch9 reviewed
Just a documentation nit and a question for you to answer. Thanks!

2024-03-23 16:15 UTC, ualch9 commented on OBAKitCore/Location/Regions/RegionsService.swift
> -    /// If an existing custom region with the same `regionIdentifier` exists, the new region replaces the existing region.
With this new file manager service, what happens if an existing custom region with the same `regionIdentifier` exists?

2024-03-23 16:15 UTC, ualch9 commented on OBAKitCore/Location/Regions/RegionsService.swift
> +    static let customRegionsPath = URL.documentsDirectory.appendingPathComponent("Regions/custom-regions")
👍

2024-03-23 16:15 UTC, ualch9 commented on OBAKitTests/Location/RegionsServiceTests.swift
>          stubRegions(dataLoader: dataLoader)
Please update the function signature comment to `saved to disk` instead of `user defaults`.

2024-03-23 16:15 UTC, ualch9 commented on OBAKitTests/Location/RegionsServiceTests.swift
>          stubRegions(dataLoader: dataLoader)
Please update the function signature comment to `saved to disk` instead of `user defaults`.

2024-04-11 02:35 UTC, aaronbrethorst commented
@aaryankotharii - need anything from me in order to get this wrapped up?

2025-04-16 22:34 UTC, closed without merging