Issue 719: Add Custom Region URL
OneBusAway/onebusaway-ios pull request #723
Opened 2024-03-28 13:31 UTC by hilmyveradin

Here's a video of working add custom region via URL:

https://github.com/OneBusAway/onebusaway-ios/assets/74521244/382d027c-654f-4666-a7ed-14478a878282

Here's a video of manage edge cases, say, when there's no name on the params:
https://github.com/OneBusAway/onebusaway-ios/assets/74521244/ca22596c-a439-4b46-8007-77e9712da02b

2024-03-28 14:44 UTC, aaronbrethorst requested changes
Go look at `Application.application(_:, open url:, options:)` to see how this should be plumbed into the app. You're going to want to extend `URLSchemeRouter` and add some tests.

2024-03-28 14:44 UTC, aaronbrethorst commented on Apps/OneBusAway/AppDelegate.m
> +    [CustomRegionDeepLink parseURL:url application:self.app];
this will break every other deep link in the app.

2024-04-04 15:14 UTC, aaronbrethorst requested changes
this looks like great progress! There are a couple small changes I'd like to see, but I think we'll be ready to go after that. thanks again for tackling this!

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKit/Orchestration/Application.swift
> +        if presentAddRegionAlertOnActive, let topViewController {
these strings all need to be localized.

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKit/Orchestration/Application.swift
> +                title: "Error",
`Strings.error`

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKit/Orchestration/Application.swift
> +            alertController.addAction(UIAlertAction(title: "OK", style: .default))
`Strings.ok`

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKit/Orchestration/Application.swift
> +                    if let regionData = regionData {
let's get rid of the pyramid of doom here:

```
guard let regionData else {
    presentAddRegionAlertOnActive = true
    return
}

guard let regionCoordinate = try await self.apiService?.getAgenciesWithCoverage().list.first?.region else {
    return
}
```

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKitCore/DeepLinks/URLSchemeRouter.swift
> +public struct AddRegionURLData {
Please add a doc comment to this struct

2024-04-04 15:14 UTC, aaronbrethorst commented on OBAKitCore/DeepLinks/URLSchemeRouter.swift
> +public enum URLType {
Please add a doc comment to this enum

2024-04-05 09:57 UTC, hilmyveradin commented
> this looks like great progress! There are a couple small changes I'd like to see, but I think we'll be ready to go after that. thanks again for tackling this!

Done, kindly check it out again!

2024-04-05 18:47 UTC, aaronbrethorst approved these changes
nice work @hilmyveradin!

2024-04-05 18:50 UTC, merged